acme/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('exercise/', include('exercise.urls'))
]

exercise/urls.py
from django.urls import path

from . import views

app_name = 'exercise'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add')
]

exercise/models.py
from django.db import models
from django.db.models.enums import IntegerChoices
from django.utils.translation import gettext as _

class Sport(models.Model):

    class Types(models.IntegerChoices):
        KM = 1,_('Km')
        COUNT = 2,_('Count')

    name = models.CharField(max_length=150)
    type = models.PositiveSmallIntegerField(choices=Types.choices)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

class Action(models.Model):

    sport = models.ForeignKey(Sport, on_delete=models.CASCADE)
    date = models.DateField()
    value = models.DecimalField(max_digits=6, decimal_places=1)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        suffix = 'km' if self.sport.type == 1 else ''
        return f'{self.sport.name} {self.value} {suffix}'

exercise/forms.py
from django import forms
from django.forms.widgets import DateInput
from .models import Action, Sport
import datetime

class ActionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ActionForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Action
        fields = ['date', 'sport', 'value']
        widgets = {
            'date': DateInput(attrs={'value': datetime.date.today, 'type': 'date'})
        }

acme/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home.html', {})

exercise/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Action
from .models import Sport
from .forms import ActionForm

def index(request):
    actions = Action.objects.order_by('-date')[:30]
    sports = Sport.objects.only('id', 'name')
    action_form = ActionForm()

    context = {
        'actions': actions,
        'sports': sports,
        'action_form': action_form
    }
    return render(request, 'exercise/index.html', context)

def add(request):

    if request.method == 'POST':
        form = ActionForm(request.POST)
        if form.is_valid():
            action = form.save()

    return HttpResponseRedirect('/exercise')

acme/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Acme - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'exercise:index' %}">Exercises</a>
                        </li>
                    </ul>
                </div>
            </div>
          </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-4">
                    {% block left-sidebar %}{% endblock %}
                </div>
                <div class="col-8">
                    {% block content %}{% endblock %}
                    <div id="vue-app"></div>
                </div>
            </div>
        </div>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

acme/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>

<p>Etusivun sisältö</p>
{% endblock %}

exercise/templates/exercise/index.html
{% extends "base.html" %}

{% block title %}Harjoitukset{% endblock %}

{% block content %}
<h1>Harjoitukset</h1>

<table class="table table-striped table-hover">
    <tr>
        <th>Päiväys</th>
        <th>Laji</th>
        <th>Arvo</th>
    </tr>
    {% for action in actions %}
        <tr>
            <td>{{ action.date }}</td>
            <td>{{ action.sport }}</td>
            <td>{{ action.value }}</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}

{% block left-sidebar %}
<h4>Lisää uusi harjoitus</h4>
<form action="{% url 'exercise:add' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {% for field in action_form %}
            <div class="mb-3">
                <label for="{{ field.html_name }}" class="form-label">{{ field.label }}</label>
                
                {{ field }}
            </div>
        {% endfor %}
    </fieldset>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}